weekly-report-config:
  host: "https://documents-api.wildberries.ru"
  methods:
    - method: "categories"
      route: "/api/v1/documents/categories"
      timeout: 10s
    - method: "list"
      route: "/api/v1/documents/list"
      timeout: 10s
    - method: "download"
      route: "/api/v1/documents/download"
      timeout: 10s
